name: Streamlit App Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit app
      run: |
        streamlit run main.py

    - name: Create executable folder for Streamlit app
      run: |
        mkdir src
        cp -r . src/

    - name: Compress src folder to src.zip
      run: |
        7z a src.zip ./src/* -r

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: src
        path: src.zip
